# Generated by Django 5.1.1 on 2025-06-24 21:03

import VigilanceAPP.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSequencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_code', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('nome_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('pix', models.CharField(blank=True, max_length=255, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True, validators=[VigilanceAPP.models.validate_cnpj])),
                ('criado_em', models.DateField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_empresas', to='VigilanceAPP.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Rondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_empresas', to='VigilanceAPP.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=12, null=True, validators=[VigilanceAPP.models.validar_cpf])),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_casa', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(default=0)),
                ('vencimento', models.IntegerField(default=1)),
                ('parcelas', models.IntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_empresas', to='VigilanceAPP.empresa')),
                ('rondas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='VigilanceAPP.rondas')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.IntegerField()),
                ('pagamento', models.DateField(blank=True, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero_casa', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='VigilanceAPP.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_empresas', to='VigilanceAPP.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='VigilanceAPP.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovante_empresas', to='VigilanceAPP.empresa')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='VigilanceAPP.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='VigilanceAPP.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
