# Generated by Django 5.1.1 on 2025-06-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaocomprovante',
            old_name='logotipo',
            new_name='logo',
        ),
    ]
