# Generated by Django 5.1.1 on 2025-06-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0002_alter_empresa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='vencimento',
            field=models.DateField(),
        ),
    ]
