# Generated by Django 5.1.1 on 2025-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0002_rename_logotipo_configuracaocomprovante_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento',
            field=models.PositiveIntegerField(),
        ),
    ]
