# Generated by Django 5.1.1 on 2025-06-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0003_alter_cliente_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento',
            field=models.IntegerField(default=1),
        ),
    ]
