# Generated by Django 5.1.1 on 2025-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0004_alter_cliente_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
