# Generated by Django 5.1.1 on 2025-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0005_titulo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
