# Generated by Django 5.1.1 on 2025-06-11 18:32

import VigilanceAPP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0006_titulo_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_casa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[VigilanceAPP.models.validate_cnpj]),
        ),
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='pix',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Rondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='VigilanceAPP.cliente')),
            ],
        ),
    ]
