# Generated by Django 5.1.1 on 2025-06-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0007_cliente_cep_cliente_numero_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parcelas',
            field=models.IntegerField(default=12),
        ),
    ]
