# Generated by Django 5.1.1 on 2025-06-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0008_cliente_parcelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rondas',
            name='clientes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rondas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='VigilanceAPP.rondas'),
        ),
    ]
