# Generated by Django 5.1.1 on 2025-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0009_remove_rondas_clientes_cliente_rondas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
