# Generated by Django 5.1.1 on 2025-06-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0010_cliente_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='numero_casa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
