# Generated by Django 5.1.1 on 2025-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0011_titulo_numero_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
