# Generated by Django 5.1.1 on 2025-06-13 20:06

import VigilanceAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0012_titulo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[VigilanceAPP.models.validar_cpf]),
        ),
    ]
