# Generated by Django 5.1.1 on 2025-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0013_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocomprovante',
            name='criado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
