# Generated by Django 5.1.1 on 2025-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0014_configuracaocomprovante_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocomprovante',
            name='pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
