# Generated by Django 5.1.1 on 2025-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VigilanceAPP', '0015_alter_configuracaocomprovante_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSequencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_code', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='titulo',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
